# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Common Application Framework
email: caf@hpe.com
description: > # this means to ignore newlines until "baseurl:"
  HPE Big Data Common Application Framework
url: "http://localhost:4000/" # the base hostname & protocol for your site
baseurl: "http://cafapi.github.io"

# Build settings
markdown: kramdown
highlighter: rouge
exclude: ['Gemfile', 'Gemfile.lock', 'node_modules']
gems: [jekyll-coffeescript, jekyll-watch, jekyll-assets]
